---
openapi: "3.1.1"
info:
  title: "Crud Demo API"
  version: "1.0.0"
paths:
  /hello:
    get:
      summary: "Returns a hello message"
      operationId: "hello"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloResponse"
  /rooms:
    post:
      tags:
      - "room"
      summary: "Add Room"
      operationId: "newRoom"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoomRequest"
      responses:
        "201":
          description: "Created"
          headers:
            Location:
              schema:
                type: "string"
              description: "URI of the created Room"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomResponse"
        "400":
          description: "Error in the request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationErrorResponse"
    get:
      tags:
      - "room"
      summary: "Retrieve all Rooms"
      operationId: "listRoom"
      responses:
        "200":
          description: "Ok"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  results:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/RoomResponse"
  /rooms/{roomId}:
    parameters:
    - $ref: "#/components/parameters/IdParam"
    get:
      tags:
      - "room"
      summary: "Retrieve Room"
      operationId: "getRoom"
      responses:
        "200":
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomResponse"
        "404":
          description: "No Room found with this RoomId"
    put:
      tags:
      - "room"
      summary: "Update Room"
      operationId: "updateRoom"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RoomRequest"
      responses:
        "200":
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomResponse"
        "400":
          description: "Error in the request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationErrorResponse"
        "404":
          description: "No Room found with this RoomId"
    delete:
      tags:
      - "room"
      summary: "Delete Room"
      operationId: "deleteRoom"
      responses:
        "200":
          description: "Ok"
        "400":
          description: "Error in the request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationErrorResponse"
        "404":
          description: "No Room found with this RoomId"
components:
  parameters:
    IdParam:
      name: "roomId"
      in: "path"
      required: true
      schema:
        type: "string"
        format: "uuid"
  schemas:
    Pagination:
      discriminator:
        propertyName: "type"
      required:
      - "total"
      - "size"
      - "index"
      properties:
        total:
          type: "number"
        index:
          type: "number"
        size:
          type: "number"
        has_next:
          type: "boolean"
        has_prev:
          type: "boolean"
    Sort:
      type: "object"
      required:
      - "field"
      - "direction"
      properties:
        field:
          type: "string"
        direction:
          type: "string"
          enum:
          - "ASC"
          - "DESC"
    HelloResponse:
      type: "object"
      properties:
        message:
          type: "string"
      required:
      - "message"
    Room:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
          readOnly: true
          description: "unique ID. Ignored in requests, required in responses"
        name:
          type: "string"
      required:
      - "name"
    RoomRequest:
      allOf:
      - $ref: "#/components/schemas/Room"
    RoomResponse:
      allOf:
      - $ref: "#/components/schemas/Room"
      required:
      - "id"
    ApplicationErrorResponse:
      type: "object"
      properties:
        message:
          type: "string"
        code:
          description: "the type of error. VALIDATION_ERROR invalid value for field\
            \ in request BAD_REQUEST error in the request format INTERNAL_SERVER_ERROR\
            \ internal server error"
          type: "string"
          enum:
          - "VALIDATION_ERROR"
          - "BAD_REQUEST"
          - "INTERNAL_SERVER_ERROR"
        errors:
          type: "array"
          items:
            type: "string"
        fieldErrors:
          description: "when code is VALIDATION_ERROR"
          type: "object"
          additionalProperties:
            type: "string"
      required:
      - "code"
      - "message"
